name: "my action custom"
description: "This is a custom action"

inputs:
  message:
    description: "name for custom"
    required: true
    default: "default message"

runs:
  using: "composite"
  steps:
    - name: "Run a script custom"
      run: echo "Hello from my custom action!  ${{ inputs.message }}"
      shell: bash
